jobs:
- name: build
  plan:
  - aggregate:
    - get: ybd
    - get: definitions
  - task: run-ybd
    privileged: true
    config:
      platform: linux
      image: "docker:///devcurmudgeon/foo"
      inputs:
      - name: ybd
      - name: definitions
      run:
        path: ybd/scripts/build.sh
        args: []
#      run:
#        path: python
#        args: ['ybd/ybd.py', 'build-essential', 'x86_64']

resources:
- name: ybd
  type: git
  source:
    uri: https://github.com/devcurmudgeon/ybd.git
    branch: concourse-foo
- name: definitions
  type: git
  source:
    uri: git://git.baserock.org/baserock/baserock/definitions.git
    branch: master